server:
  port: ${APP_PORT}

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  session:
    data:
      redis:
        repository-type: indexed

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  issuer-uri: http://localhost:${APP_PORT}
  mfa:
    encryption-key: ${MFA_ENCRYPTION_KEY}
