package com.sozureke.auth_server.audit;

public enum AuditEventType {
  LOGIN,
  LOGIN_FAILED,
  LOGOUT,
  REGISTER,
  PASSWORD_CHANGE,
  MFA_ENABLE,
  MFA_DISABLE,
  TOKEN_ISSUED,
  TOKEN_REVOKED,
  USER_DISABLED,
  USER_DELETED,
  USER_FORCE_LOGOUT,
  CLIENT_CREATED,
  CLIENT_UPDATED,
  CLIENT_DELETED,
  CLIENT_SECRET_ROTATED
}
